// DO NOT EDIT MANUALLY, let automation work hard.
// auto-generated by PinoutLogic.java based on config/boards/mikrus_df/connectors/*.yaml
// For now this file was hand-written to match main.yaml; regenerate with gen_config.sh once the board is registered.

#include "pch.h"

const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A0:
			return "AN7 - Analog 7";
		case Gpio::A1:
			return "AN8 - Analog 8";
		case Gpio::A2:
			return "12V Battery Sense";
		case Gpio::A4:
			return "WiFi CS";
		case Gpio::A5:
			return "WiFi SCK";
		case Gpio::A6:
			return "WiFi MISO";
		case Gpio::A7:
			return "WiFi MOSI";
		case Gpio::B0:
			return "WiFi Reset";
		case Gpio::B1:
			return "WiFi IRQ";
		case Gpio::B4:
			return "IN2 - Injector 2";
		case Gpio::B5:
			return "IN3 - Injector 3";
		case Gpio::B6:
			return "IN4 - Injector 4";
		case Gpio::B7:
			return "IN5 - Injector 5";
		case Gpio::B8:
			return "IN6 - Injector 6";
		case Gpio::B9:
			return "IN7 - Injector 7";
		case Gpio::C0:
			return "AN3 - Analog 3 / CLT";
		case Gpio::C1:
			return "AN4 - Analog 4 / IAT";
		case Gpio::C2:
			return "AN5 - Analog 5";
		case Gpio::C3:
			return "AN6 - Analog 6";
		case Gpio::C4:
			return "AN1 - Analog 1";
		case Gpio::C5:
			return "AN2 - Analog 2 / MAP";
		case Gpio::C6:
			return "HALL1 - Primary Trigger";
		case Gpio::D3:
			return "IGN2 - Ignition 2";
		case Gpio::D4:
			return "IGN1 - Ignition 1";
		case Gpio::D7:
			return "IN1 - Injector 1";
		case Gpio::D10:
			return "ETB Direction";
		case Gpio::D11:
			return "ETB Disable";
		case Gpio::D12:
			return "ETB PWM";
		case Gpio::E3:
			return "LED Red / Error";
		case Gpio::E4:
			return "LED Green 1 / Comms";
		case Gpio::E5:
			return "LED Green 2 / Running";
		case Gpio::E6:
			return "LED Orange / Warning";
		case Gpio::E7:
			return "VR1 - VR/Hall Input";
		case Gpio::E11:
			return "HALL2 - Secondary Trigger";
		default:
			return nullptr;
	}
	return nullptr;
}
